contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #galxc channel"
    url: https://nfcore.slack.com/channels/galxc
    about: Discussion about the nf-core/galxc pipeline
